version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRESQL_PASSWORD=pw00
      - POSTGRESQL_DATABASE=shorturl
    volumes:
      - postgres_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=pw00
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  postgres_data:
  redis_data:
